- name: Create automation.yaml
  env:
    APP_USERNAME: ${{ secrets.APP_USERNAME }}
    APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
  run: |
    mkdir -p zap

    cat > zap/automation.yaml <<EOF
    env:
      contexts:
        - name: QA
          urls:
            - https://dev-ui.schneider.xrdashboard.com

          authentication:
            method: form
            parameters:
              loginPageUrl: "http://devopswithmahesh.shop/api/auth/login"
              loginRequestUrl: "http://devopswithmahesh.shop/api/auth/login"
              loginRequestBody: "email=$APP_USERNAME&password=$APP_PASSWORD"

          sessionManagement:
            method: cookie

          users:
            - name: zap-user

    jobs:
      - type: spider
        parameters:
          context: QA
          user: zap-user

      - type: activeScan
        parameters:
          context: QA
          user: zap-user

      - type: report
        parameters:
          reportDir: /zap/wrk
          reportFile: report.html
          template: traditional-html
    EOF
