env:
  contexts:
    - name: QA
      urls:
        - https://dev-ui.schneider.xrdashboard.com

      authentication:
        method: form
        parameters:
          loginPageUrl: "https://dev-ui.schneider.xrdashboard.com/login/Schneider"
          loginRequestUrl: "https://dev-ui.schneider.xrdashboard.com/login/Schneider"
          loginRequestBody: "email=${{ secrets.APP_USERNAME }}&password=${{ secrets.APP_PASSWORD }}"

      sessionManagement:
        method: cookie

      users:
        - name: zap-user

jobs:
  - type: spider
    parameters:
      context: QA
      user: zap-user

  - type: activeScan
    parameters:
      context: QA
      user: zap-user

  - type: report
    parameters:
      reportDir: /zap/wrk
      reportFile: report.html
      template: traditional-html